### ISSUE TITLE
Revamp the Goal Setting Algorithm

### ISSUE THREAD

**Issue by zghera** [Autonomous-Motorsports-Purdue/AMP_ASSv1#31]
## Description
The current goal-setting algorithm is able to navigate around the [autocross map](https://github.com/Autonomous-Motorsports-Purdue/AMP_ASSv1/blob/master/src/kart_2dnav/maps/autocross.png) in simulation (either when provided a map or [for the first lap](https://github.com/Autonomous-Motorsports-Purdue/AMP_ASSv1/issues/18) when the map is not provided).

However, there are a number of problems that have been noted with the goal-setting algorithm. These include
* (flaky/inconsistent) The kart can find itself too close to a wall, resulting in one of the following:
    * The simulation ends because the kart is too close to the wall
    * The kart turns around 180 and drives in the opposite direction
    * The kart stops, backs up, and resumes driving
* Very sensitive to wall distance deviations when the kart is far from the wall. This has caused overcorrections that lead to the previously listed item.
* ...

## Sub-tasks
- [ ] Either re-writing the goal-setting algorithm from scratch or tune/modify the existing algorithm to fix the issues listed above as well as any other critical issues observed during development (add those as comments in this issue please).

- [ ] Make sure your code follows the [AMP Dev Guide](https://docs.google.com/document/d/12pxTRj222Epa1dPj1StSx_5ltzKU0ssKErxQkieUkwc/edit?usp=sharing)
  - [ ] Write unit tests.
  - [ ] Include useful logs (see **ADD ISSUE REGARDING STANDARDIZING AND FIGURING OUT LOGGING HERE**).
  - [ ] Follow the Google Python style guide.

## Other Useful Information
* [This document](https://docs.google.com/document/d/1Ao1DKd2Ywco3HMOQu0uPS8jJ3yg6HB3BlfkFv77QYgk/edit?usp=sharing) described some of the issues seen with goal setting. Some of the items listed (namely number 4) may not be in scope for this PR.

**Comment by YKim0172** [comment]
For one of the issues mentioned above ("The kart stops , backs up, and resumes driving"), one solution I thought of was modifying the step size of the kart so that there's more time for the kart to process its surroundings.  

Of course, the main caveat of this fix (assuming it will resolve the issue) is that the kart won't be going as fast and move in a more jerky fashion.

**Comment by YKim0172** [comment]
One other issue that I think is crucial to solve our issues outlined above is to make find a way to make the Lidar make a much more accurate image of its surroundings. This issue is evident starting from 0:25 in the following video [https://user-images.githubusercontent.com/39711376/103718929-e378d380-4f95-11eb-806f-ed28c6e52c6f.mp4]. Despite there being plenty of space in the bottom right part of the autocross map, for some reason, the kart thinks that there is a wall instead, so it tries to squeeze between the narrow gap.

**Comment by zghera** [comment]
@YKim0172 Nice observations so far. I updated the issue description, with the [link to the GH Wiki for the goal setting algorithm ](https://github.com/Autonomous-Motorsports-Purdue/AMP_ASSv1/wiki/Goal-Setting-Algorithm) that you and the team should update. 

So please put these observations and future stuff in that wiki.
