### ISSUE TITLE
Dockerize AMP_ASSv1

### ISSUE THREAD

**Issue by alanssitis** [Autonomous-Motorsports-Purdue/AMP_ASSv1#44]
## Description
Dockerize current iteration of AMP_ASSv1. Implement CI for automated upload to Docker Hub and make sure it runs adequately and as expected on the Jetson.

## Sub-tasks
- [ ] Implement Docker file
- [ ] Implement CI workflow
- [ ] Test on Jetson

## Other
If interested in this issue, contact me (@alanssitis) and claim it in the comments under.

## Resources
* https://hackernoon.com/how-to-dockerize-any-application-b60ad00e76da
* http://wiki.ros.org/docker/Tutorials/Docker
* http://wiki.ros.org/docker/Tutorials/GUI
* https://docs.docker.com/get-started/overview/
